---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/repositories/interview_practice/phone_number

                go build  -o /tmp/interview_practice/phone_number .
                /tmp/interview_practice/phone_number
