---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/code/interview_practice/exponent

                go build  -o /tmp/interview_practice/exponent .
                /tmp/interview_practice/exponent
