---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/repositories/interview_practice/concurrency

                go build  -o /tmp/interview_practice/concurrency .
                /tmp/interview_practice/concurrency



