---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/code/interview_practice/ahmed

                go build  -o /tmp/interview_practice/ahmed .
                /tmp/interview_practice/ahmed
