---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/code/interview_practice/two_sum

                go build  -o /tmp/interview_practice/two_sum .
                /tmp/interview_practice/two_sum
